name: Ebozor
description: Ebozor is your go-to classified app for buying and selling new and used items in your local community. Whether you're looking to declutter your home, score great deals, or find unique items, Ebozor makes it easy to connect with buyers and sellers in your area.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev [Be careful]

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.2.0
  firebase_messaging: ^15.1.3
  flick_video_player: ^0.9.0
  youtube_player_flutter: ^9.1.1
  country_picker: ^2.0.26
  connectivity_plus: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.6.0
  image_picker: ^1.1.2
  file_picker: ^8.1.3 #^8.0.7
  flutter_bloc: ^8.1.6
  shimmer: ^3.0.0
  cached_network_image: ^3.4.0
  dotted_border: ^2.1.0
  url_launcher: ^6.3.0
  #flutter_html: ^3.0.0-beta.2
  share_plus: ^10.0.0
  in_app_review: ^2.0.9
  lottie: ^3.1.2
  mime_type: ^1.0.1
  awesome_notifications: ^0.10.0
  device_preview: ^1.2.0
  path_provider: ^2.1.4
  record: ^6.1.2
  audioplayers: ^6.1.0
  image_cropper: ^8.0.2
  permission_handler: ^11.3.1
  open_filex: ^4.5.0
  package_info_plus: ^8.0.2
  #label_marker: ^1.0.1
  #flutter_typeahead: ^5.2.0
  any_link_preview: ^3.0.0
  geocoding: ^3.0.0
  encrypt: ^5.0.3
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.1
  geolocator: ^13.0.1
  flutter_svg: ^2.0.9
  #uni_links: ^0.5.1
  #google_maps_webservice: ^0.0.19
  google_mobile_ads: ^5.1.2
  flutter_image_compress: ^2.3.0
  google_maps_flutter: ^2.9.0
  vibration: ^2.0.0
  device_region: ^1.4.0
  flutter_pdfview: ^1.3.2
  app_links: ^6.3.1
  change_app_package_name: ^1.3.0
  video_player: ^2.9.1
  path: ^1.9.0
  #payment gateways
  flutter_stripe: ^11.3.0
  in_app_purchase: ^3.2.0 #^3.2.0
  #flutter_paystack: ^1.0.7
  razorpay_flutter: ^1.3.7
  device_info_plus: ^11.1.0
  sms_autofill: ^2.4.0
  webview_flutter: ^4.9.0
  flutter_widget_from_html: ^0.15.2
  intl: ^0.20.0
  record_linux: ^1.2.1
  animated_text_kit: ^4.3.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  socket_io_client: ^3.1.3
  #flutter_keyboard_visibility: ^6.0.0
  #pay_with_paystack:



dependency_overrides:
  #intl: ^0.17.0
#  flutter_paystack:
#    git:
#      url: https://github.com/I-driod/flutter_paystack.git
#      ref: master



dev_dependencies:
  rename: ^3.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/svg/
    - assets/svg/bottomnav/
    - assets/languages/
    - assets/lottie/
    - assets/chat_background/
    - assets/svg/Logo/
    - assets/svg/Illustrators/
    - assets/svg/payment/
    - assets/


  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
flutter_icons:
  android: true
  ios: false
  image_path: "assets/svg/Logo/splashlogo.png"










